- 1기(2020.10)/eyabc/step01.md
[자바스크립트 aribnb 스타일 가이드](https://github.com/airbnb/javascript)
[1. Types](https://eyabc.github.io/Doc/dev/Airbnb_JS_Style_Guides/Types.html)
[2. References](https://eyabc.github.io/Doc/dev/Airbnb_JS_Style_Guides/References.html)
[3. Arrays](https://eyabc.github.io/Doc/dev/Airbnb_JS_Style_Guides/Arrays.html)
[4. Destructuring](https://eyabc.github.io/Doc/dev/Airbnb_JS_Style_Guides/Destructuring.html)
[5. Strings](https://eyabc.github.io/Doc/dev/Airbnb_JS_Style_Guides/Strings.html)
[6. Functions](https://eyabc.github.io/Doc/dev/Airbnb_JS_Style_Guides/Functions.html)
한달 전 쯤부터 조금씩 읽어보았는데 두고두고 참고하면 좋을 것 같아 블로그에 적어보았습니다 
Function 까지는 eslint 내용 읽어가면서 정리가 되어있고 나머지 부분은 eslint 내용을 포함하지 않는 것들도 있어 8번으로 남겨두고 있습니다
자바스크립트 aribnb 스타일 가이드 읽어보면서 블랙커피 스터디하면서 적용도 해본것 같아 기분이 좋았네요
블로그에는 제맘대로 다 줄임말을 써서 가독성이 안좋을 …
> [1기 eyabc] 자바스크립트 airbnb 스타일 가이드 

- 1기(2020.10)/devJang/step-1.md
개인 블로그에 포스팅을 했습니다!
번거롭지만 링크타고 확인 부탁드립니다 :)
[링크](https://devjang.github.io/2020/10/17/2020-10-17-woowahan-tech-learning-3rd)
> [1기 장현석] 우아한 테크러닝 3기 React & TypeScript 후기

- 1기(2020.10)/hongjehong/step.md
https://zyggie.tistory.com/1
부족한 글이지만 아무쪼록 잘 부탁드립니다.
> [1기 홍현의] 2020 하반기 코딩 테스트 회고

- 1기(2020.10)/ganeodolu/step1.md
- [첫번째 블로그](https://www.notion.so/1-44cfa7d0de9547ab9f052215fc38f49c)
이번 블로그는 아래의 블로그들을 읽고 난 소감을 간략히 적어보았습니다. 첫 블로그라 그런지 전체공개 일기를 쓰는 느낌이 드네요. 제가 자신에게 얘기하듯이 편하게 작성하였습니다. :frog:
- [개발자가 적성에 맞는지?](https://brocess.tistory.com/305)
- [소프트웨어 학습태도](https://brunch.co.kr/@godrm77/16?fbclid=IwAR0w6cY_Ore68oFxwqmG1awHdop-BXXqv4YQ3_T5maBUjdBOXKDg4w51be8)
> [1기 가너도루] "개발자가 적성에 맞는지? feat. 7년차 개발자"를 읽고

- 2기(2020.11)/rutgo/step1.md
안녕하세요. 첫 포스팅입니다!
이번 주에 있던 if kakao 2020에서 관심있는 발표가 있어 보고 정리한 내용입니다.
JUnit5를 10개월 동안 쓰고 있었지만 아직 잘 모르는 기능들이 참 많은거 같습니다.
이번에 배운 새로운 기능들을 하나씩 써보는 시간을 가져봐야 할거 같네요!
그럼 잘 부탁드리겠습니다 🙏
https://rutgo-letsgo.tistory.com/172
> [2기 김세윤][1주차] [if(kakao)2020] JUnit5를 시작하며

- 2기(2020.11)/toneyparky/step1.md
안녕하세요 반갑습니다. 토니에요🙂
[첫번째 글](https://toneyparky.tistory.com/51) 제출합니다~
앞으로 남은 기간 동안 재미있게 스터디해봐요😬
감사합니다!
> [2기 toneyparky] 1주차 : 글을 왜 안 쓰는가

- 2기(2020.11)/allen/step01.md
안녕하세요!? 김홍빈입니다.
이번에 스프링시큐리티를 공부하면서 포스팅을 정리하게 됐어요.
아무래도 복잡하다보니 스터디기간동안은 스프링시큐리티관련된 포스팅을 할 것 같아요. 😃
[링크](https://velog.io/@allen/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0%EC%99%80-%EC%9D%B8%EC%A6%9D) 에서 볼 수 있어요!
다들 화이팅입니다~!
> [2기 김홍빈][1주차] 11월 3주차 스프링시큐리티와 인증

- 2기(2020.11)/그니/slack-logging.md
안녕하세요. 그니입니다. :) 
블랙커피 블로그 스터디 [2기 첫 글](https://www.notion.so/99c54aed5a9d4c7992161d19d0b4f1ef) 제출합니다.
프로젝트 팀원들에게 전달하려는 목적으로 작성한 글이었어서 지루할 수도 있을 것 같아요. 😥
그냥 편하게 읽어주시면 감사하겠습니다!!
잘 부탁드려요!
> [2기 그니][1주 차] 슬랙 로깅 적용하기

- 2기(2020.11)/makerjun/websocket.md
안녕하세요! 그니입니다.
이번에는 WebSocket 기술에 대해서 정리해보았습니다.
저도 다른 분들처럼 회고나 앞으로의 다짐 등에 대해서 작성해보고 싶은데, 취업 준비 중이라 아직은 여유가 없네요. ㅠㅠ
2기 블로그 스터디가 끝나기 전에 꼭 한 번은 작성해보겠습니다!
편하게 보려면 [여기](https://www.notion.so/WebSocket-4a38bf5e93104567b1b0b488ded51dd3)를 눌러주세요!
> [2기 그니][2주 차] WebSocket 기술에 대하여

- 2기(2020.11)/rutgo/step2.md
2주차 글이 조금 늦었네요.
최근 취준하느라 CS공부 위주로 하고 있는데, MVC 패턴에 대해 정리를 해봤습니다!
부족한 부분이 많아서...ㅎㅎ 너무 간단한 이야기일수도 있을 수도 있지만 잘 부탁드리겠습니다 👍
> [2기 김세윤][2주차] MVC 패턴이란?

- 2기(2020.11)/allen/step01.md
- 2기(2020.11)/allen/stop02.md
안녕하세요!? 김홍빈입니다.
이번에는 저번 시큐리티에 연장선인 글인데요...!
생각보다 쉽지않네요 ㅠㅠ 또 포스팅도 늦었네요😂 
잘 부탁드립니다.
> [2기 김홍빈][2주차] 스프링시큐리티의 인가

- 2기(2020.11)/toneyparky/step2.md
안녕하세요..!
정신없이 김장을 하다보니 때를 놓쳐서 조금 늦게 글을 올립니다😇
[이제는 오늘이 된 12월을 즐겁고 알차게 보내기 위해서 무얼하면 좋을지에 대해서 써보았어요.](https://toneyparky.tistory.com/52)
다 이뤄내는 멋쟁이가 되어보겠습니다😎
아, 김장은 너무 맛있게 잘 됐답니다.
> [2기 toneyparky][2주차] 12월을 어찌 보낼까

- 3기(2021.01)/Jun/navigationtiming.md
- 3기(2021.01)/Jun/throttle_debounce.md
Navigation Timing API와 페이지 로딩 순서에 대해서 정리해봤습니다.
신입이라 항상 배워가는 입장이며, 정보의 정확도 또한 많이 떨어집니다.
잘못된 부분이나 추가할 부분이 있다면 편하게 코멘트 부탁드립니다 ^__^
https://www.notion.so/4112143f5564448598374f79865d70f4
> [3기 Jun][1주차] Navigation Timing API

- 3기(2021.01)/pje1740/step1.md
안녕하세요, 3기 블로그 스터디 참가하는 박소현이라고 합니다. 
아직 배워가는 단계라 부족하거나 틀린 이야기가 적혀있을 수도 있습니다. 
혹 그런 부분이 있다면 편하게 말씀 주세요!! :)
https://stitchcoding.tistory.com/38
> [3기 pje1740][1주차] You Don't Know JS Yet - Scope & Closures 요약 및 감상 (2)클로저

- 3기(2021.01)/jho2301/step1.md
[https://onwah.tistory.com/24](https://onwah.tistory.com/24)
요즘 스타트업 창업 강의를 듣고있는데 자연스럽게 서비스 기획에 대한 관심이 생기네요
개발공부, 취업준비가 1순위여야 하지만 ㅎㅎ..
영국정부의 웹서비스 설계원칙에 대해서 번역하고 나름의 느낀점을 달아보았습니다!
> [3기 전환오][1주차] 영국 정부의 디지털 서비스 설계 원칙

- 3기(2021.01)/Jun/throttle_debounce.md
Debounce And Throttle에 대해서 정리해봤습니다.
잘못된 부분이나 추가할 부분이 있다면 편하게 코멘트 부탁드립니다 ^__^
https://jooonho.com/web/2021-01-31-debounced-throttle/
> [3기 Jun][2주차] Debounce And Throttle

- 3기(2021.01)/TheWing/step2.md
안녕하세요 블랙커피 3기 참여자 TheWing입니다
한 주 동안 공부한 내용들과 포스팅한 글입니다
블랙커피 스터디 2주차 학습 방법에 대한 고민
- [블랙커피 스터디 2주차 학습 방법에 대한 고민](https://sujl95.tistory.com/69)
백기선님 LiveStudy
- [11주차 과제: Enum](https://sujl95.tistory.com/66)
REST API 정리
- [REST API](https://sujl95.tistory.com/68)
Be-Docs 스터디 TDD 발표 후기
- [Be-Docs 스터디 TDD 발표 후기](https://sujl95.tistory.com/70)
>  [3기 TheWing][2주차] 블랙커피 스터디 2주차 학습 방법에 대한 고민

- 3기(2021.01)/OhGun/step01.md
[3기 OhGun][3주차]step01을 작성해보았습니다
> [3기 OhGun][3주차]깃허브 PR에 대해 알게 되었습니다

- .gitignore
- 3기(2021.01)/abcdsds/step3.md
이번에 회사 업무로 injector를 만들면서 까먹지 않기 위해
기록 겸해서 남겨봤습니다.
https://www.notion.so/Pod-Injection-dc0d1d96a6e548249a184e5928809326
> [3기 abcdsds][3주차] 나만의 쿠버네티스 injector 만들기

- 3기(2021.01)/TheWing/step3.md
뒤 늦게 올립니다..
한 주 동안 공부한 내용들과 포스팅한 글입니다
이번 한 주는 바빠서 LiveStudy만 올렸습니다..
백기선님 LiveStudy
- [12주차 과제: 애노테이션](https://sujl95.tistory.com/67)
- [13주차 과제: I/O](https://sujl95.tistory.com/71)
> [3기 TheWing][3주차] 블랙커피 스터디 , LiveStudy(Enum, Annotation)

- 3기(2021.01)/Jun/singleton_weakMap.md
- 3기(2021.01)/Jun/throttle_debounce.md
[singleton_weakMap에 대해서 ](https://www.notion.so/Singleton-WeakMap-08d4ec328b3c444d8854beff431d6404)
> [3기 Jun][3주차] SingleTon 패턴과 WeakMap에 대해서

- README.md
title: 자바 제네릭스
description: 자바의 정석을 읽고 정리했습니다.
category: 강의정리
link: [블로그 링크](https://velog.io/@meme2367/JAVA-Generic)
>  [4기 명다연] 자바 제네릭스

- README.md
title:  RDBMS의 동시성 제어 
description: RDBMS에서 동시성을 제어하는 방법
category: 공부
link: https://syundev.tistory.com/283
> [4기-1주차-박상윤] RDBMS의 동시성 제어

- 4기(2021.03)/3week.md
title: 2021년 2월 회고  
description: 게임 출시 준비로 보낸 2월을 돌아보며    
category: 회고  
link: [[회고] 2021년 2월 회고](https://www.notion.so/2021-2-43ca747dd2254e808ce5a4e0d3d4d12a)
> [4기 lettuce] [3주차] [회고] 2021년 2월 회고

- README.md
title: AWS 실수 모음  
description: AWS 실수 모음입니다.
category: AWS
link: [2021-03-22 AWS 실수 모음](https://wani-coding.tistory.com/154)
> [4기 oen142 김종완] [3주차] AWS 실수 모음  

- README.md
title: 블랙커피 프론트엔드 스터디 회고
description: 블랙커피 프론트엔드 스터디를 진행하며 배운점과 느꼈던 소감을 정리해봅니다.
category: 회고
link: [블랙커피 프론트엔드 스터디 회고](https://www.notion.so/bffb14daea984293a954ac7cdb4f7c1e)
> [4기 최인혁] [4주차] 블랙커피 프론트엔드 스터디 회고

- README.md
title: First Step
description: 이번 글은 1분기 회고입니다.
category: 회고
link: [블로그 링크](https://kingjky.github.io/daily/2021/daily210419.html)
> [5기 kingjky][1주차] First Step

- README.md
title: Level1 미션 + 학습 로그 정리
description: 우아한테크코스의 Level1 과정에서 배운 것을 학습로그를 통해 정리합니다
category: 회고
link: [Level1 미션 + 학습 로그 정리](https://papimon.tistory.com/79)
> [5기 조엘] [2주차] Level1 미션 + 학습 로그 정리

- README.md
title: 1장 - 웹과 네트워크의 기본에 대해 알아보자 외 3개
description: 책을 읽고 새로 배운 내용에 대해 정리했습니다.
category: 학습
link:
[웹과 네트워크의 기본에 대해 알아보자 - 그림으로 배우는 http & network basic 1장](https://www.notion.so/pkeu/1-df10db1f96474f569d3a3ad74dbdde51)
[DBMS의 특징과 SQL - SQL 첫걸음 1강](https://www.notion.so/pkeu/1-9f28a4154c154e468b5f529a5c6f5725)
[Hello World 실행하기 - SQL 첫걸음 4강](https://www.notion.so/pkeu/4-7b61acb202874ee98552d133c7ea51e5)
[테이블 구조 참조하기 - SQL 첫걸음 5강](https://www.notion.so/pkeu/5-cdeccc9f9a0e459f94e2902ca6dc4dde)
[검색 조건 지정하기 - SQL 첫걸음 6강](https://www.notion.so/pkeu/6-f0e80a9337c14f6fbd7937dc3b9c3d71)
> [5기 피케이] [2주차] 책 읽고 내용 정리

- README.md
title: 저는 소켓이 처음이라니까요?
description: 소켓이 무엇인지, 어떻게 동작하는지 공부해본다. 
category: 기술블로그
link: [저는 소켓이 처음이라니까요?](https://papimon.tistory.com/80)
> [5기 조엘][4주차][저는 소켓이 처음이라니까요?]

- README.md
|내가 Vim을 사용하는 이유|기술블로그|Vim에 빠져든 과정과 그 이유에 대한 소회입니다.|[링크](https://www.notion.so/Vim-aa12aa53ba0a4b2f87dfde83fce5def9)|
> [6기 inhyuck][2주차] 내가 Vim을 사용하는 이유

- README.md
|하루회고|회고|짧은 시간에 작성한 오늘 하루 회고입니다|[링크](https://www.notion.so/04a8b26d6d64429fa59bdecb92d65a8e)|
> [6기 inhyuck] [4주차] 하루회고

- README.md
|2021년 상반기 회고|회고|2021년 상반기 회고와 하반기 계획입니다.|[링크](https://www.notion.so/2021-7f1f30f11e9a4042bc1e5fe40650a573)|
> [7기 inhyuck] [1주차] 2021년 상반기 회고

- README.md
|우아한테크캠프 4기를 시작하며..|회고|우아한 테크캠프 합격후기, 잡담|[링크](https://kowoohyuk.tistory.com/136)|
|우아한테크캠프 4기 1주차 회고|회고|우아한 테크캠프 첫 프로젝트 후기|[링크](https://kowoohyuk.tistory.com/137)|
> [7기 json] [1주차] 우아한테크캠프 합격 후기, 첫 프로젝트 후기

- README.md
|좋은 스타트업?|회고|VC 투자에 대한 강의를 듣고 저의 생각을 정리해봤습니다|[https://papimon.tistory.com/87](https://papimon.tistory.com/87)|
> [7기 조엘][3주차] 좋은 스타트업?

- README.md
|모던 자바스크립트 Deep Dive와 프로그래밍 그리고 나의 생각|생각|모던 자바스크립트 책 서문 요약과 이와 관련된 내 생각을 적어본다.|[링크](https://www.notion.so/Deep-Dive-158b465377ac4623b9e6ed42fd9daa8c)|
> [7기 inhyuck][3주차] 모던 자바스크립트 Deep Dive와 프로그래밍 그리고 나의 생각

- README.md
|회고의 회고|회고|회고를 제대로 작성하고 있는지에 대한 회고입니다. :)|[링크](https://kowoohyuk.tistory.com/140)|
> [7기 json] [3주차] 회고의 회고

- README.md
|루티너리를 이용한 아침 루틴 형성|일상|'루티너리' 앱을 2주간 사용하며 느낀 아침 루틴 형성을 위한 경험을 공유합니다.|[링크](https://rain-digit-eb9.notion.site/09943a25e8684fb48f3a8b11f129e0bf)|
> [7기 inhyuck][4주차] 루티너리를 이용한 아침 루틴 형성

- README.md
|우아한테크캠프 4기 두 번째 프로젝트 회고|회고|회고의 회고대로 회고를 바꿔봤습니다... :) 아직은 많이 부족하네요!|[링크](https://kowoohyuk.tistory.com/141)|
> [7기 json] [4주차] 우아한테크캠프 4기 두 번째 프로젝트 회고
